// Generated by i18nline.
import I18n from 'i18nline';

/*[I18N_CONFIG_PLACEHOLDER]*/

I18n.import = locale => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		/*[I18N_IMPORT_PLACEHOLDER]*/
		default: return import(/* webpackChunkName: 'i18n.default' */ './default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	/*[I18N_RELOAD_PLACEHOLDER]*/
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
