// Generated by i18nline.
import I18n from 'i18nline';

I18n.import = locale => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		/*[IMPORT_LOCALES_PLACEHOLDER]*/
		default: return import('./default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	/*[RELOAD_LOCALES_PLACEHOLDER]*/
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
